require regenerator-runtime
This fixes the following error, introduced in #7.

    ReferenceError: regeneratorRuntime is not defined

https://github.com/babel/babel/issues/9849